// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncuintyupxbsvzanolsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jdWludHl1cHhic3Z6YW5vbHN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODM4NTUsImV4cCI6MjA2NDU1OTg1NX0.rLl0XIRLNu6NGyIRoeI4e-FMt1F0d07tt9LbZpfQHCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});